### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by naeem76** [Ryochan7/DS4WindowsWPF#1]
I will try to contribute in my free time, I have experience with WPF and MVVM, If you have a list of sorts for missing features and such, can you include it in the Readme.md, I will dive deep into the project later myself.

Also have you taken look at Mahapps.Metro? I used to that for WPF before

**Comment by Ryochan7** [comment]
I guess I can write up some sort of task list later. Right now, the main focus has just been getting the main window working like the current DS4Form in DS4Windows. Profile selection was a recent addition so now the application is slightly usable. It isn't a fair comparison yet but the WPF version is slightly snappier even in the mapping routines so far.

I have not looked into Mahapps.Metro. I am trying to keep assembly dependency down to a minimum so I would hesitate adding a reference until it is needed. The Extended WPF Toolkit and Hardcodet NotifyIcon are the extra assembly references being used right now.

**Comment by Ryochan7** [comment]
Except for running some tests, the WPF version is pretty much finished now. It turned out fine and application performance is a good amount better than the stable Windows Forms build. Here is a link to the recent beta build.

https://drive.google.com/file/d/1Jq0jMmvj4jHUw2sq4nq9rCpdw1ZfTJtl/view?usp=sharing
